In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

url = "Iris.csv"


# Assign colum names to the dataset
# names = ['points','x1','x2','y']

# Read dataset to" pandas dataframe
dataset = pd.read_csv(url)


In [ ]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
y[0:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.80)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 13)
classifier.fit(X_train, y_train) 

KNeighborsClassifier(n_neighbors=13)

In [ ]:
X_test

array([[ 0.45005635, -2.02080117,  0.45755244,  0.42977473],
       [-1.70065542, -0.4328938 , -1.27927928, -1.24634671],
       [ 0.80850832, -0.20604989,  1.18590123,  1.33230166],
       [-0.14736358, -1.34026944,  0.73768659,  1.07443682],
       [-0.38633156, -1.34026944,  0.17741829,  0.17190989],
       [ 0.33057237, -0.20604989,  0.68165976,  0.81657198],
       [-1.46168745,  0.24763794, -1.27927928, -1.24634671],
       [ 0.68902433, -0.65973771,  1.07384757,  1.20336924],
       [ 0.09160439, -0.20604989,  0.79371342,  0.81657198],
       [-0.38633156,  0.92816967, -1.3353061 , -1.24634671],
       [ 1.04747629, -1.34026944,  1.18590123,  0.81657198],
       [ 0.33057237, -0.65973771,  0.5696061 ,  0.04297747],
       [ 1.76438022, -0.4328938 ,  1.46603537,  0.81657198],
       [-0.26684757, -0.4328938 , -0.04668902,  0.17190989],
       [ 0.33057237, -0.65973771,  0.17741829,  0.17190989],
       [-0.14736358, -0.20604989,  0.28947195,  0.04297747],
       [ 1.04747629, -0.

In [ ]:
y_test

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred



array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("confusion matrix: \n",confusion_matrix(y_test, y_pred))

print("classification report:\n ",classification_report(y_test, y_pred))

print("Accuracy score: ", accuracy_score(y_test,y_pred)*100)

confusion matrix: 
 [[ 7  0  0]
 [ 0 11  1]
 [ 0  0 11]]
classification report:
                   precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

Accuracy score:  96.66666666666667


In [ ]:
z = classifier.predict([[ -1.70065542, -0.4328938 , -1.27927928, -1.24634671]])
z

array(['Iris-setosa'], dtype=object)